name: Quotes

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Your normal steps go here.
      # Added:
      - name: Config git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
      - name: All files end with newline
        run: for f in $(git grep --cached -Il ''); do tail -c1 $f | read -r _ || echo >> $f; done
