name: Quotes

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Your normal steps go here.
      # Added:
      - name: All files end with newline
        run: echo >> pwd
